spring.application.name=springMvc
spring.datasource.url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.username=postgres
spring.datasource.password=example

#spring.profile.active = TORNEO_DAO_JDBC_PREPAREDSTATEMENT

spring.profile.active = TORNEO_DAO_JDBC_STATEMENT
