spring.application.name=springbatch


spring.datasource-torneo.jdbcUrl=jdbc:postgresql://localhost:5432/torneobatch
spring.datasource-torneo.username=postgres
spring.datasource-torneo.password=example
spring.datasource-torneo.driver-class-name=org.postgresql.Driver

#spring.datasource.pippoUrl=jdbc:postgresql://localhost:5432/demospringbatch
#spring.datasource.username=postgres
#spring.datasource.password=example
#spring.datasource.driver-class-name=org.postgresql.Driver
