spring.application.name=springMvc
spring.datasource.url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web: DEBUG'
