spring.application.name=springbatch

spring.datasource.torneo.jdbc-url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.torneo.username=postgres
spring.datasource.torneo.password=example
spring.datasource.torneo.driver-class-name=org.postgresql.Driver
spring.datasource.torneo.jpa.hibernate.ddl-auto=update
spring.datasource.torneo.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.batch.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.batch.driver-class-name=org.h2.Driver
spring.datasource.batch.username=sa
spring.datasource.batch.password=
spring.datasource.batch.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=DEBUG
logging.level.com.baeldung=TRACE